config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index', :as => 'search_page'


  post 'payment/create', to: 'payment#create'
  post 'payment/execute', to: 'payment#execute'


  resources :registrants
  resources :domains
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/registrant.rb
class Registrant < ApplicationRecord
    has_many :addresses
    accepts_nested_attributes_for :addresses
end

app/controllers/registrants_controller.rb
class RegistrantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_registrant, only: [:show, :edit, :update, :destroy]

  def index
    @registrants = Registrant.all
  end


  def show
  end


  def new
    @registrant = Registrant.new
  end


  def edit
  end


  def create

    @registrant = Registrant.new(registrant_params)
    respond_to do |format|
      if @registrant.save
        format.html { redirect_to @registrant, notice: 'Registrant was successfully created.' }
        format.json { render :show, status: :created, location: @registrant }
      else
        format.html { render :new }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @registrant.update(registrant_params)
        format.html { redirect_to @registrant, notice: 'Registrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @registrant }
      else
        format.html { render :edit }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @registrant.destroy
    respond_to do |format|
      format.html { redirect_to registrants_url, notice: 'Registrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_registrant
      @registrant = Registrant.find(params[:id])
      puts @registrant
    end

    def registrant_params
      params.require(:registrant).permit(:voice, :fax, :email, 
        addresses_attributes: [
          :id,
          :street,
          :city,
          :state,
          :postalcode,
          :countrycode
        ], 
        postal_info_attributes:[
          :id,
          :name,
          :organization
        ]
      )

    end
end

app/views/registrants/_form.html.erb
<%= form_with(model: registrant, local: true) do |form| %>

  <% if registrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registrant.errors.count, "error") %> prohibited this registrant from being saved:</h2>

      <ul>
      <% registrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :voice %>
    <%= form.text_field :voice %>
  </div>

  <div class="field">
    <%= form.label :fax %>
    <%= form.text_field :fax %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <%= form.fields_for :addresses_attributes do |a| %>
        <div class="field">
        <%= a.label :street %>
        <%= a.text_field :street %>
        </div>

        <div class="field">
          <%= a.label :city %>
          <%= a.text_field :city %>
        </div>

        <div class="field">
          <%= a.label :state %>
          <%= a.text_field :state %>
        </div>

        <div class="field">
          <%= a.label :postalcode %>
          <%= a.text_field :postalcode %>
        </div>

        <div class="field">
          <%= a.label :countrycode %>
          <%= a.text_field :countrycode %>
      </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registrants</h1>

<table>
  <thead>
    <tr>
      <th>Voice</th>
      <th>Fax</th>
      <th>Email</th>
      <th>Address</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registrants.each do |registrant| %>
      <tr>
        <td><%= registrant.voice %></td>
        <td><%= registrant.fax %></td>
        <td><%= registrant.email %></td>
        <% registrant.addresses.each do |address_attr|%>
        <td><%= address_attr.street %> <%= address_attr.city %> <%= address_attr.state %></td>
        <%end%>
        <td><%= link_to 'Show', registrant %></>
        <td><%= link_to 'Edit', edit_registrant_path(registrant) %></td>
        <td><%= link_to 'Destroy', registrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registrant', new_registrant_path %>

app/views/registrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voice:</strong>
  <%= @registrant.voice %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @registrant.fax %>
</p>

<p>
  <strong>Email:</strong>
  <%= @registrant.email %>
</p>

<%= link_to 'Edit', edit_registrant_path(@registrant) %> |
<%= link_to 'Back', registrants_path %>