config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index', :as => 'search_page'


  post 'payment/create', to: 'payment#create'
  post 'payment/execute', to: 'payment#execute'


  resources :registrants
  resources :domains
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end

    def search  
        if params[:search].blank?  
            redirect_to(root_path, notice: 'Domain unavailable') and return  
          else
            @parameter = params[:search].downcase  
            @results = Domain.all.where("lower(name) LIKE :search", search: @parameter)  
            format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
            
          end  
        @results = Domain.all.where("lower(name) LIKE :search", search: @parameter) 
        @results.inspect
    end
    
end

app/views/home/_form.html.erb
<%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search Domain", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "",:name => nil%>  
    </div>  
  </div>  
<% end %>

app/views/home/index.html.erb
<h1>WELCOME HOMEE</h1>

<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search Domain", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "",:name => nil%>  
    </div>  
  </div>  
<% end %>


<td><%= link_to 'Domains', new_domain_path %></td>