config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index', :as => 'search_page'


  post 'payment/create', to: 'payment#create'
  post 'payment/execute', to: 'payment#execute'


  resources :registrants
  resources :domains
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/domain.rb
class Domain < ApplicationRecord
    has_one :price ,  dependent: :destroy 

    accepts_nested_attributes_for :price, allow_destroy: true
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render json: @domain, status: :ok, location: @domain }
        
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def domain_params
      params.require(:domain).permit(:name, :registration_date, :expiration_date, 
        price_attributes:
        [
          :id,
          :price_cents,
          :pricecurrency,
          :_destroy
      ])
    end
end

app/views/domains/_form.html.erb
<%= form_with(model: domain, local: true) do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :registration_date %>
    <%= form.datetime_select :registration_date %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.datetime_select :expiration_date %>
  </div>

    <%= form.fields_for :price_attributes do |domain_price| %>
    
      <div class="field">
        <%= domain_price.label :price_cents %>
        <%= domain_price.text_field :price_cents, :readonly => true, id: 'price-cent'%>   
            <select  id="domain_desired_attribute" onchange="getddl()">
              <option value="1 year">1 year</option>
              <option value="2 year">2 years</option>
              <option value="5 year">5 years</option>
              <option value="10 year">10 years</option>
            </select>
      </div>
      <script>
          // var cent = document.getElementById("price-cent");
          // var period = document.getElementById("domain_desired_attribute");
          // var domainPeriod = formid.ddlselect[formid.ddlselect.selectedIndex].text;
          var form = document.getElementById("formid");
          
          //    console.log(domainPeriod);
          //    if (domainPeriod === '1 year') {
          //      cent.value = '35';
          //    }
         
            var cent = document.getElementById("price-cent");
            var period = document.getElementById("domain_desired_attribute").value;
            var form = document.getElementById("formid");

               if (period === '1 year') {
                  cent.value = '35';
               }
         
       </script>
    <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
 <input type = 'text' value = <%= @domain.name %> readonly id='domain-name'/>
</p>

<p>
  <strong>Registration date:</strong>
  <input type = 'text' value = <%= @domain.registration_date %> readonly  id='registration-date'/>
</p>

<p>
  <strong>Expiration date:</strong>
 <input type = 'text' value = <%= @domain.expiration_date %> readonly id = 'expiration-date' />
</p>


<div id="paypal-checkout"></div>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
  paypal.Button.render({
    env: "sandbox",
    client: {
      sandbox: "AW4I8tHeTC_xdRHrcvpgD2RgBHC-QlhnNO3uP_ZyUjpCanJbxbMvM3qI9nbnSv2ZtrMf_jNOZMuJV055"
    },
    style: {
      layout: 'vertical',
      size:  'medium',
      shape: 'rect',
      color: 'blue',
    },
    commit: true,
    funding: {
      allowed: [paypal.FUNDING.CARD],
      disallowed: [paypal.FUNDING.CREDIT]
    },
    payment: function(data, actions) {

      var domainName = document.getElementById("domain-name").value;
      var regDate = document.getElementById("registration-date").value;
      var expDate = document.getElementById("expiration-date").value;

      params = {domain: domainName , registration: regDate, expiration: expDate}
  
      createPath = "http://localhost:3000/payment/create"
      return actions.request.post(createPath, params).then(function(response) {
        return response.id;
      });
    },
    onAuthorize: function(data, actions) {
      params = {payment_id: data.paymentID, payer_id: data.payerID}

      executePath = "http://localhost:3000/payment/execute"
      return actions.request.post(executePath, params).then(function(response) {
        if (response.payment_state == "approved") {
          javascript:window.location.href = 'http://localhost:3000' // Replace this with your successful registration page
          
        }
      });
    },
    onError: function (err) {
      alert('Error!');
    }
  }, '#paypal-checkout');
</script>


<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>